name: Deploy a WSL

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Copiar archivos al servidor
        run: |
          rsync -av --delete ./ /var/www/html/app/