name: Deploy a WSL

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Copiar archivos al servidor
        run: |
          rsync -av --exclude='.github' $GITHUB_WORKSPACE/ /var/www/html/app/

      - name: Recargar NGINX
        run: sudo service nginx reload

      - name: Verificar permisos
        run: |
          sudo chown -R david:david /var/www/html/app/
          sudo chmod -R 755 /var/www/html/app/